### ISSUE TITLE
Game window closes but process continues to run when changing resolution settings in game

### ISSUE THREAD

**Issue by mikkurogue** [YaLTeR/niri#3021]
I play alot of WoW, and I run it through Faugus Launcher. It does the trick usually but sometimes I notice a few problems;
- Changing anything in terms of resolution or game quality where something like texture resolution would affect output or scaling (anything that causes the window to change some property) the window itself will just disappear, but the process will stay running `niri msg windows` also does not find it, but any sounds etc are still able to be heard.
- Sometimes the game will "fail" to launch (actually just does what is above) when it needs to maximize the window. Only fix I've found is re-installing.
- Sometimes the UI scaling persists to just be incredibly terrible and text for instance is very low quality while the rest is just fine. At first I thought I just needed to set the environment variable `WINE_FULLSCREEN_INTEGER_SCALING=1` but sometimes it just doesnt work at all.

Of course its running through xwayland as is the case with any Wine/proton game so I doubt its entirely niri's fault.

I dont have this issue with Hyprland (there are however other issues with Hyprland but this somehow isnt one). I think the window is somehow being orphaned but I'm not sure whats going on. Sometimes none of these issues happen at all either, its not consistent.

I'm also unsure if this is then window behaviour or something with wayland satellite, as in hyprland we can just configure xwayland directly and I have never had this specific issue on there.

<details><summary>Config</summary>

These are the window rules I have for WoW and battlenet/steam

```kdl
input {
    keyboard {
        xkb {
            layout "us,fi"
            options "grp:alt_shift_toggle"
        }
        numlock
    }
    touchpad {
        tap
       natural-scroll
    }

    mouse {
        accel-speed 0.25
        accel-profile "flat"
    }

    trackpoint {
   }
}

output "DP-2" {
    mode "2560x1440@155"
    scale 1
    transform "normal"
    position x=0 y=0
}

output "DP-3" {
    mode "1920x1080@144"
    scale 1
}

layout {
    gaps 12 
    background-color "#14131E"
   
    center-focused-column "never"

    preset-column-widths {
        proportion 0.33333
        proportion 0.5
        proportion 0.66667
    }

    default-column-width { proportion 0.5; }
    focus-ring {
        width 1 
        active-color "#7fc8ff"
        inactive-color "#505050"
    }

    border {
        off
        width 4
        active-color "#ffc87f"
        inactive-color "#505050"
        urgent-color "#9b0000"
    }

    shadow {
       softness 30
        spread 5
        offset x=0 y=5
        color "#0007"
    }

    struts {
   }
}

spawn-at-startup "/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1"
spawn-at-startup "awww-daemon"
spawn-at-startup "awww" "img" "/home/mikku/Pictures/Wallpapers/arch.png"
spawn-at-startup "waybar" "-c" "/home/mikku/.config/waybar/config-niri.jsonc" "-s" "/home/mikku/.config/waybar/css/style-niri.css"
spawn-at-startup "dunst"
spawn-at-startup "swayosd-server"
spawn-at-startup "xembedsniproxy"
spawn-at-startup "systemctl" "--user" "set-environment" "WINE_FULLSCREEN_INTEGER_SCALING=1"
// Set XKB layout for XWayland apps
spawn-at-startup "setxkbmap" "-layout" "us,fi" "-option" "grp:alt_shift_toggle"
spawn-at-startup "discord"
// Start Steam silently (minimized to tray)
spawn-at-startup "steam" "-silent"

hotkey-overlay {
    // skip-at-startup
}

animations {
}

// Open the Firefox picture-in-picture player as floating by default.
window-rule {
    match app-id=r#"firefox$"# title="^Picture-in-Picture$"
    open-floating true
}

// Always spawn Discord on DP-3 monitor
window-rule {
    match app-id=r#"discord"#
    open-on-output "DP-3"
    open-maximized true
}

// Allow Steam games to open fullscreen
// Allow Steam games to open fullscreen (exclude steam_app_0 which is Battle.net)
window-rule {
    match app-id=r#"^steam_app_[1-9]"#
    open-fullscreen true
}

// World of Warcraft - fullscreen (through Battle.net/steam_app_0)
window-rule {
    match title=r#"World of Warcraft"#
    open-maximized true
}

// Battle.net main window - tiled, not fullscreen
window-rule {
    match app-id=r#"^steam_app_0$"# title=r#"Battle\.net"#
    open-fullscreen false
    default-column-width { fixed 1920; }
}

binds {
   Mod+Shift+Slash { show-hotkey-overlay; }

    Mod+T hotkey-overlay-title="Open a Terminal: ghostty" { spawn "ghostty"; }
    Mod+Space hotkey-overlay-title="Run an Application Launcher: wofi" { spawn "wofi" "--show" "drun"; }
    Mod+F hotkey-overlay-title="Open browser: firefox" { spawn "firefox"; }
    Mod+E hotkey-overlay-title="Open file manager: dolphin" { spawn "dolphin"; }

    Ctrl+Alt+W hotkey-overlay-title="Toggle Waybar" { spawn-sh "pkill waybar || exec waybar -c /home/mikku/.config/waybar/config-niri.jsonc -s /home/mikku/.config/waybar/css/style-niri.css " ; }
    Super+Alt+S allow-when-locked=true hotkey-overlay-title=null { spawn-sh "pkill orca || exec orca"; }
    Mod+S hotkey-overlay-title="Take Screenshot" { spawn-sh "grim -g \"$(slurp -d)\" - | wl-copy"; }

    XF86AudioRaiseVolume allow-when-locked=true { spawn-sh "wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.1+"; }
    XF86AudioLowerVolume allow-when-locked=true { spawn-sh "wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.1-"; }
    XF86AudioMute        allow-when-locked=true { spawn-sh "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"; }
    XF86AudioMicMute     allow-when-locked=true { spawn-sh "wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"; }

    Mod+O repeat=false { toggle-overview; }

    Mod+Q repeat=false { close-window; }

    Mod+Left  { focus-column-left; }
    Mod+Down  { focus-window-down; }
    Mod+Up    { focus-window-up; }
    Mod+Right { focus-column-right; }
    Mod+H     { focus-column-left; }
    Mod+J     { focus-window-down; }
    Mod+K     { focus-window-up; }
    Mod+L     { focus-column-right; }

    Mod+Ctrl+Left  { move-column-left; }
    Mod+Ctrl+Down  { move-window-down; }
    Mod+Ctrl+Up    { move-window-up; }
    Mod+Ctrl+Right { move-column-right; }
    Mod+Ctrl+H     { move-column-left; }
    Mod+Ctrl+J     { move-window-down; }
    Mod+Ctrl+K     { move-window-up; }
    Mod+Ctrl+L     { move-column-right; }

      Mod+Home { focus-column-first; }
    Mod+End  { focus-column-last; }
    Mod+Ctrl+Home { move-column-to-first; }
    Mod+Ctrl+End  { move-column-to-last; }

    Mod+Shift+Left  { focus-monitor-left; }
    Mod+Shift+Down  { focus-monitor-down; }
    Mod+Shift+Up    { focus-monitor-up; }
    Mod+Shift+Right { focus-monitor-right; }
    Mod+Shift+H     { focus-monitor-left; }
    Mod+Shift+J     { focus-monitor-down; }
    Mod+Shift+K     { focus-monitor-up; }
    Mod+Shift+L     { focus-monitor-right; }

    Mod+Shift+Ctrl+Left  { move-column-to-monitor-left; }
    Mod+Shift+Ctrl+Down  { move-column-to-monitor-down; }
    Mod+Shift+Ctrl+Up    { move-column-to-monitor-up; }
    Mod+Shift+Ctrl+Right { move-column-to-monitor-right; }
    Mod+Shift+Ctrl+H     { move-column-to-monitor-left; }
    Mod+Shift+Ctrl+J     { move-column-to-monitor-down; }
    Mod+Shift+Ctrl+K     { move-column-to-monitor-up; }
    Mod+Shift+Ctrl+L     { move-column-to-monitor-right; }

      Mod+Page_Down      { focus-workspace-down; }
    Mod+Page_Up        { focus-workspace-up; }
    Mod+U              { focus-workspace-down; }
    Mod+I              { focus-workspace-up; }
    Mod+Ctrl+Page_Down { move-column-to-workspace-down; }
    Mod+Ctrl+Page_Up   { move-column-to-workspace-up; }
    Mod+Ctrl+U         { move-column-to-workspace-down; }
    Mod+Ctrl+I         { move-column-to-workspace-up; }

      Mod+Shift+Page_Down { move-workspace-down; }
    Mod+Shift+Page_Up   { move-workspace-up; }
    Mod+Shift+U         { move-workspace-down; }
    Mod+Shift+I         { move-workspace-up; }

    Mod+WheelScrollDown      cooldown-ms=150 { focus-workspace-down; }
    Mod+WheelScrollUp        cooldown-ms=150 { focus-workspace-up; }
    Mod+Ctrl+WheelScrollDown cooldown-ms=150 { move-column-to-workspace-down; }
    Mod+Ctrl+WheelScrollUp   cooldown-ms=150 { move-column-to-workspace-up; }

    Mod+WheelScrollRight      { focus-column-right; }
    Mod+WheelScrollLeft       { focus-column-left; }
    Mod+Ctrl+WheelScrollRight { move-column-right; }
    Mod+Ctrl+WheelScrollLeft  { move-column-left; }

    Mod+Shift+WheelScrollDown      { focus-column-right; }
    Mod+Shift+WheelScrollUp        { focus-column-left; }
    Mod+Ctrl+Shift+WheelScrollDown { move-column-right; }
    Mod+Ctrl+Shift+WheelScrollUp   { move-column-left; }
    Mod+1 { focus-workspace 1; }
    Mod+2 { focus-workspace 2; }
    Mod+3 { focus-workspace 3; }
    Mod+4 { focus-workspace 4; }
    Mod+5 { focus-workspace 5; }
    Mod+6 { focus-workspace 6; }
    Mod+7 { focus-workspace 7; }
    Mod+8 { focus-workspace 8; }
    Mod+9 { focus-workspace 9; }
    Mod+Ctrl+1 { move-column-to-workspace 1; }
    Mod+Ctrl+2 { move-column-to-workspace 2; }
    Mod+Ctrl+3 { move-column-to-workspace 3; }
    Mod+Ctrl+4 { move-column-to-workspace 4; }
    Mod+Ctrl+5 { move-column-to-workspace 5; }
    Mod+Ctrl+6 { move-column-to-workspace 6; }
    Mod+Ctrl+7 { move-column-to-workspace 7; }
    Mod+Ctrl+8 { move-column-to-workspace 8; }
    Mod+Ctrl+9 { move-column-to-workspace 9; }

   Mod+BracketLeft  { consume-or-expel-window-left; }
    Mod+BracketRight { consume-or-expel-window-right; }

    Mod+Comma  { consume-window-into-column; }
    Mod+Period { expel-window-from-column; }

    Mod+R { switch-preset-column-width; }
    Mod+Shift+R { switch-preset-window-height; }
    Mod+Ctrl+R { reset-window-height; }
    Mod+B { maximize-column; }
    Mod+Shift+F { fullscreen-window; }

    Mod+Ctrl+F { expand-column-to-available-width; }

    Mod+C { center-column; }

    Mod+Ctrl+C { center-visible-columns; }

    Mod+Minus { set-column-width "-10%"; }
    Mod+Equal { set-column-width "+10%"; }

    Mod+Shift+Minus { set-window-height "-10%"; }
    Mod+Shift+Equal { set-window-height "+10%"; }

    Mod+V       { toggle-window-floating; }
    Mod+Shift+V { switch-focus-between-floating-and-tiling; }

    Mod+W { toggle-column-tabbed-display; }

       Print { screenshot; }
    Ctrl+Print { screenshot-screen; }
    Alt+Print { screenshot-window; }
    Mod+Escape allow-inhibiting=false { toggle-keyboard-shortcuts-inhibit; }

    Mod+Shift+E { quit; }
    Ctrl+Alt+Delete { quit; }
    Mod+Shift+P { power-off-monitors; }
}
```

</details> 

### System Information

* niri version: niri 25.11 (b35bcae)

* Distro: Arch Linux

* GPU: AMD RX7600XT

* CPU: Ryzen 5 5600X

**Comment by Sempyos** [comment]
Send your full config

**Comment by mikkurogue** [comment]
Ah turns out I needed to do a few things to make it more consistent. I'll update if it happens again, but essentially I had to add a few things to my config to ensure some wine stuff;

```
spawn-at-startup "xembedsniproxy"
spawn-at-startup "systemctl" "--user" "set-environment" "WINE_FULLSCREEN_INTEGER_SCALING=1"
spawn-at-startup "setxkbmap" "-layout" "us,fi" "-option" "grp:alt_shift_toggle"
```

The first and third options are only relevant for me here, but I think i needed to not register the `WINE_FULLSCREEN_INTEGER_SCALING` in my systemd config but for some reason just run it on startup for the session. sometimes the environment didnt seem to load properly.



> Send your full config

In terms of this, my config is essentially the default config with just a few spawn commands like above, the window rules for steam_app_x and some keybinds nothing extra special except maybe the monitor configuration. I have updated the OP with the full config withoutv the comments, i try to stay "close ish to default" im a simple man

**Comment by Sempyos** [comment]
Thanky, so is the uh issue less present now with the stuff you mentioned above or..?

**Comment by mikkurogue** [comment]
Yeah, seems like it. I'll close for now and if it happens again I'll see if it's (again) a skill issue or if something else is going on.

**Comment by Sempyos** [comment]
Thanks

**Comment by Vildravn** [comment]
I am getting the same problem, also with World of Warcraft launched through Battle.net that is added to Steam as a Non-Steam game. Seems to only be happening since the last release of niri. Same exact symptoms, but on launch. Launching battle.net is fine, pressing the Play button then results in the game window appearing momentarily, presumably trying to resize itself and disappearing. Audio is still audible but the game window is not shown in `niri msg windows`.

I tried setting the `WINE_FULLSCREEN_INTEGER_SCALING` env var the same way but no change.

Here's my config, with most of the comments removed. It's largely the default config
<details><summary>Details</summary>
<p>

```kdl
input {
    keyboard {
        xkb {
            layout "se"
        }

        numlock
    }

    touchpad {
        off
    }

    mouse {
        accel-profile "adaptive"
    }

    trackpoint {
        off
    }
}

layout {
    gaps 16

    center-focused-column "never"
    always-center-single-column

    preset-column-widths {
        proportion 0.33333
        proportion 0.5
        proportion 0.66667
    }

    default-column-width { proportion 0.5; }
    focus-ring {
        width 1

        active-color "#c4a7e7"

        inactive-color "#6e6a86"
    }

    border {
        off

        width 2
        active-color "#ffc87f"
        inactive-color "#505050"

        urgent-color "#9b0000"
    }

    shadow {
        softness 30
        spread 5
        offset x=0 y=5
        color "#0007"
    }

    struts {
    }
}

spawn-at-startup "waybar"
// Fixes for changing resolutions in games (WoW launch bug)
// https://github.com/YaLTeR/niri/issues/3021
spawn-at-startup "systemctl" "--user" "set-environment" "WINE_FULLSCREEN_INTEGER_SCALING=1"

environment {
    DISPLAY ":0"
}

prefer-no-csd

screenshot-path "~/Pictures/Screenshots/Screenshot from %Y-%m-%d %H-%M-%S.png"

animations {
}

window-rule {
    match app-id=r#"^org\.wezfurlong\.wezterm$"#
    default-column-width {}
}

window-rule {
    match app-id=r#"firefox$"#
    match app-id=r#"^com\.mitchellh\.ghostty$"#
    match app-id=r#"^vivaldi-stable$"#

    open-maximized true
}

window-rule {
    match app-id=r#"firefox$"# title="^Picture-in-Picture$"
    open-floating true
}

binds {
    Mod+Shift+Slash { show-hotkey-overlay; }
    Mod+F1 { show-hotkey-overlay; }

    Mod+T hotkey-overlay-title="Open a Terminal: Ghostty" { spawn "ghostty"; }
    Mod+D hotkey-overlay-title="Run an Application: fuzzel" { spawn "fuzzel"; }
    Super+Alt+L hotkey-overlay-title="Lock the Screen: swaylock" { spawn "swaylock"; }

    XF86AudioRaiseVolume allow-when-locked=true { spawn "wpctl" "set-volume" "@DEFAULT_AUDIO_SINK@" "0.1+"; }
    XF86AudioLowerVolume allow-when-locked=true { spawn "wpctl" "set-volume" "@DEFAULT_AUDIO_SINK@" "0.1-"; }
    XF86AudioMute        allow-when-locked=true { spawn "wpctl" "set-mute" "@DEFAULT_AUDIO_SINK@" "toggle"; }
    XF86AudioMicMute     allow-when-locked=true { spawn "wpctl" "set-mute" "@DEFAULT_AUDIO_SOURCE@" "toggle"; }

    Mod+O repeat=false { toggle-overview; }

    Mod+Q { close-window; }

    Mod+Left  { focus-column-left; }
    Mod+Down  { focus-window-down; }
    Mod+Up    { focus-window-up; }
    Mod+Right { focus-column-right; }
    Mod+H     { focus-column-left; }
    Mod+J     { focus-window-down; }
    Mod+K     { focus-window-up; }
    Mod+L     { focus-column-right; }

    Mod+Ctrl+Left  { move-column-left; }
    Mod+Ctrl+Down  { move-window-down; }
    Mod+Ctrl+Up    { move-window-up; }
    Mod+Ctrl+Right { move-column-right; }
    Mod+Ctrl+H     { move-column-left; }
    Mod+Ctrl+J     { move-window-down; }
    Mod+Ctrl+K     { move-window-up; }
    Mod+Ctrl+L     { move-column-right; }

    Mod+Home { focus-column-first; }
    Mod+End  { focus-column-last; }
    Mod+Ctrl+Home { move-column-to-first; }
    Mod+Ctrl+End  { move-column-to-last; }

    Mod+Shift+Left  { focus-monitor-left; }
    Mod+Shift+Down  { focus-monitor-down; }
    Mod+Shift+Up    { focus-monitor-up; }
    Mod+Shift+Right { focus-monitor-right; }
    Mod+Shift+H     { focus-monitor-left; }
    Mod+Shift+J     { focus-monitor-down; }
    Mod+Shift+K     { focus-monitor-up; }
    Mod+Shift+L     { focus-monitor-right; }

    Mod+Shift+Ctrl+Left  { move-column-to-monitor-left; }
    Mod+Shift+Ctrl+Down  { move-column-to-monitor-down; }
    Mod+Shift+Ctrl+Up    { move-column-to-monitor-up; }
    Mod+Shift+Ctrl+Right { move-column-to-monitor-right; }
    Mod+Shift+Ctrl+H     { move-column-to-monitor-left; }
    Mod+Shift+Ctrl+J     { move-column-to-monitor-down; }
    Mod+Shift+Ctrl+K     { move-column-to-monitor-up; }
    Mod+Shift+Ctrl+L     { move-column-to-monitor-right; }

    Mod+Page_Down      { focus-workspace-down; }
    Mod+Page_Up        { focus-workspace-up; }
    Mod+U              { focus-workspace-down; }
    Mod+I              { focus-workspace-up; }
    Mod+Ctrl+Page_Down { move-column-to-workspace-down; }
    Mod+Ctrl+Page_Up   { move-column-to-workspace-up; }
    Mod+Ctrl+U         { move-column-to-workspace-down; }
    Mod+Ctrl+I         { move-column-to-workspace-up; }

    Mod+Shift+Page_Down { move-workspace-down; }
    Mod+Shift+Page_Up   { move-workspace-up; }
    Mod+Shift+U         { move-workspace-down; }
    Mod+Shift+I         { move-workspace-up; }

    Mod+WheelScrollDown      cooldown-ms=150 { focus-workspace-down; }
    Mod+WheelScrollUp        cooldown-ms=150 { focus-workspace-up; }
    Mod+Ctrl+WheelScrollDown cooldown-ms=150 { move-column-to-workspace-down; }
    Mod+Ctrl+WheelScrollUp   cooldown-ms=150 { move-column-to-workspace-up; }

    Mod+WheelScrollRight      { focus-column-right; }
    Mod+WheelScrollLeft       { focus-column-left; }
    Mod+Ctrl+WheelScrollRight { move-column-right; }
    Mod+Ctrl+WheelScrollLeft  { move-column-left; }

    Mod+Shift+WheelScrollDown      { focus-column-right; }
    Mod+Shift+WheelScrollUp        { focus-column-left; }
    Mod+Ctrl+Shift+WheelScrollDown { move-column-right; }
    Mod+Ctrl+Shift+WheelScrollUp   { move-column-left; }

    Mod+1 { focus-workspace 1; }
    Mod+2 { focus-workspace 2; }
    Mod+3 { focus-workspace 3; }
    Mod+4 { focus-workspace 4; }
    Mod+5 { focus-workspace 5; }
    Mod+6 { focus-workspace 6; }
    Mod+7 { focus-workspace 7; }
    Mod+8 { focus-workspace 8; }
    Mod+9 { focus-workspace 9; }
    Mod+Ctrl+1 { move-column-to-workspace 1; }
    Mod+Ctrl+2 { move-column-to-workspace 2; }
    Mod+Ctrl+3 { move-column-to-workspace 3; }
    Mod+Ctrl+4 { move-column-to-workspace 4; }
    Mod+Ctrl+5 { move-column-to-workspace 5; }
    Mod+Ctrl+6 { move-column-to-workspace 6; }
    Mod+Ctrl+7 { move-column-to-workspace 7; }
    Mod+Ctrl+8 { move-column-to-workspace 8; }
    Mod+Ctrl+9 { move-column-to-workspace 9; }

    Mod+BracketLeft  { consume-or-expel-window-left; }
    Mod+BracketRight { consume-or-expel-window-right; }

    Mod+Comma  { consume-window-into-column; }
    Mod+Period { expel-window-from-column; }

    Mod+R { switch-preset-column-width; }
    Mod+Shift+R { switch-preset-window-height; }
    Mod+Ctrl+R { reset-window-height; }
    Mod+F { maximize-column; }
    Mod+Shift+F { fullscreen-window; }

    Mod+Ctrl+F { expand-column-to-available-width; }

    Mod+C { center-column; }

    Mod+Ctrl+C { center-visible-columns; }

    Mod+Minus { set-column-width "-10%"; }
    Mod+Equal { set-column-width "+10%"; }

    Mod+Shift+Minus { set-window-height "-10%"; }
    Mod+Shift+Equal { set-window-height "+10%"; }

    Mod+V       { toggle-window-floating; }
    Mod+Shift+V { switch-focus-between-floating-and-tiling; }

    Mod+W { toggle-column-tabbed-display; }

    Print { screenshot; }
    Ctrl+Print { screenshot-screen; }
    Alt+Print { screenshot-window; }

    Mod+Escape allow-inhibiting=false { toggle-keyboard-shortcuts-inhibit; }

    Mod+Shift+E { quit; }
    Ctrl+Alt+Delete { quit; }

    Mod+Shift+P { power-off-monitors; }
}
```

</p>
</details> 

**System Information**
* NixOS Unstable (26.05)
* niri 25.11
* xwayland-satellite 0.8.0
* GPU: AMD Radeon RX 6800XT
* CPU: AMD Ryzen 3600X
* 2 identical screens

**Comment by mikkurogue** [comment]
> Same exact symptoms, but on launch.

I had the same issue too on launch, funnily enough when opening the Midnight Beta I didnt have any of these issues either (no weird scaling issue, no window being orphaned while the WoW.exe process still runs in the background). I dont know what the difference is there other than the beta launcher is a totally different thing to retail/classic.

The way I eventually fixed it, which I dont think is really a fix per se but I felt it to be fine, was to outright uninstall the game and re-install it. Some temporary fixes, for the current session at least, were to remove WTF and back up the AccountData folders in wow/_retail_ but that's not a reasonable ask to do every time.

When changing settings in game it will still orphan the window with the running process so I think it's either some window event not caught or some xwayland shenanigans (or both).

I'd recommend trying that, or updating the wine prefix stuff with a different proton runner, but otherwise I dont really know. I still get some of the weird scaling issues but once I just click play it works just fine (other some cursor problems but that's not something I think is a niri problem but more of "xwayland stinks" type of deal)

**Comment by Vildravn** [comment]
> funnily enough when opening the Midnight Beta I didnt have any of these issues

Interesting, same here..... I guess I'll dive into the configs and try to find if there's some interfering setting. Thanks for the pointer.

**Comment by mikkurogue** [comment]
if you figure it out, let me know :D I can only think of some weird wineprefix/proton settings that _may_ cause the window to be lost in the vacuum of space, but I wouldnt expect a window resolution change to also be orphaned either but im too stupid to actually know whats going on with how wayland/xwayland deals with these things

**Comment by fifty-six** [comment]
I'm also experiencing this issue - though just when I swap between monitors a lot with a fullscreen game open. It's always been a wine thing - haven't had this happen with any native apps - but same behavior. Game window disappears but I can still hear the audio and it still seems to be running in the bg.

**Comment by Vildravn** [comment]
@mikkurogue So this took a while, I had a workaround to launch BattleNet and WoW with `PROTON_ENABLE_WAYLAND=1`
I had to launch and quit BNet with wayland disabled at first, because there's a bug that doesn't let you through security with Wayland enabled.. but the session persists a bit .... annoying but usable, anyway...

Today, I accidentally launched WoW with Wayland disabled and my window actually stuck around. I don't know why that would be, but I installed two addons recently - Interaction and Dialogue UI. Diffing the `Config.wtf` I can see that one of those set a new CVar:
```
SET cameraFov "90"
```

It doesn't make any sense to me but that's the only meaningful difference. See if that works for you.

**Comment by rkanati** [comment]
if this is actually still a possible niri problem @mikkurogue should re-open

**Comment by mikkurogue** [comment]
yeah i still have the issue but its not always consistent, i do have to sometimes re-open battle.net from either faugus launcher or from my .desktop shortcut and i have to have some weird black box running next to it that opens that then no longer causes any scaling issues etc. i havent had the problem yet with the window being orphaned though as i dont mess with settings anymore in game.

re-opening then:)

**Comment by mikkurogue** [comment]
@Vildravn 
I was just playing around with some stuff, and I also noticed that there are some other weird (x)wayland issues specifically around WoW (I think anyway). The WINE env variable doesnt actually do anything, but if I enable this settings in Faugus Launcher to start Bnet with the experimental Wayland driver then the scaling is fixed. The window being orphaned when changing settings in game however still occurs.

<img width="843" height="647" alt="Image" src="https://github.com/user-attachments/assets/6aa2cb25-d47b-4ac2-81d4-30259f0338fc" />

The window closing is still something I havent yet been able to work past, even with removing all window rules, so I'm thinking it has to have something to do with xwayland-satellite (i can only assume really) that some event is either not caught or something is invalid for niri to consider it a real window?

**Comment by Dzubrul** [comment]
I have the same issue as @fifty-six while playing Armored Core VI, switching the focus between monitor will sometime make the Armored Core window disappear. The process will die after some time but the wine process related to Armored Core will live on unless I kill it to restart the game.

**Comment by hownioni** [comment]
I have a similar issue to @Dzubrul on Fallout 4 when switching focus to another window. The game process continues and I have to forcefully quit it. On Qtile when something like this happened there is a key-bind to toggle minimized windows so you can see them again.
This gets fixed by using proton-ge to run the game

**Comment by siemato** [comment]
I ran into the same issue with WoW Classic.
After quite a bit of debugging, the trigger is specifically the window becoming fully hidden — in my case through workspace switching. As long as the WoW window remains even partially visible (e.g. scrolled half off-screen in niri's layout), everything works fine. The moment it's completely off-screen, the window vanishes while the process keeps running. No errors in niri's journal at all when it happens.

I also tried the buffer size fix from #3253 (wl_display_set_default_max_buffer_size set to 1 MiB, same as swaywm/sway#8532) — it didn't help. These seem to be two separate issues.

Gamescope with --backend wayland doesn't produce a window on niri either, so that's not a viable workaround.
What does work is running Wine with a virtual desktop (explorer /desktop=WoW,<resolution>). Since Wine manages its own internal windows inside the virtual desktop container, the game is insulated from whatever happens to the X11 surface when the Wayland surface is hidden. Not ideal, but functional.

My best guess is that xwayland-satellite is destroying or unmapping the X11 surface when niri stops compositing the corresponding Wayland surface on a workspace switch. I hope that helps a bit.

**Comment by CanadaBry** [comment]
Recently started having this issue with games as well.

Sometimes while changing focus to another monitor, the xwayland window for a game (running through proton/wine) disappears while I continue to hear game audio. The process also still exists and needs to be killed manually.

This has happened for me with a steam game, Palworld, and a Lutris installed game, Guild Wars.

I haven't determined an exact trigger, just that it seems to happen when changing focus away from the game (In my case they are full screen).

This issue didn't occur with my previous installation of Niri, but after moving to a fresh install of CachyOS (and using their niri dot files) it started occurring sporadically.

**Comment by mikkurogue** [comment]
I havent experienced it as much lately (I still do sometimes), mostly however the sharpness issues have returned (which I can only chalk up to xwayland-satellite not having a force_zero_scaling type setting).

I can still easily orphan my window by just changing the in game resolution, I can do this with almost any game that "re-mounts" the window after a resolution change though not every game does this or at least much less consistent

**Comment by k-e-l-p** [comment]
Been dealing with this with ArmA3 ever since I started using niri; and have also been running into similar issues with Hyprland, before i swapped over. The specific trigger in my case is exhaustion of my GPU's resources, namely, VRAM. My current, go-to, most reliable workaround is to run sway for the duration of my session. Not great; but workable, given that i play it once per weekend.

I don't think that this is caused by niri specifically, but rather by smithay. I opened an issue there a few months ago to radio silence: https://github.com/Smithay/smithay/issues/1988 

I did a bit more digging today and found a small trove of seemingly unlinked issues and PRs. The issue, to me, seems to be the fact that Smithay is unable to properly handle GPU resets. Here's everything that I found:

#### Smithay-adjacent

https://github.com/Smithay/smithay/issues/978
https://github.com/Smithay/smithay/issues/1932
https://github.com/pop-os/cosmic-comp/pull/2097 (This one is interesting: mentions a driver setting, viable workaround? will test)

---

#### The upstream fix:

There's a wayland protocol that is supposed to provide a common means to 'invalidate' a surface, thus, somehow managing a full reset? The issues above mention this as the canonical solution; however, the issue is stalled. Also, given that it mentions patches to `mpv`, `foot`, `swaybg`, it seems that clients will also need to implement this protocol as well to handle things properly. I assume that means an additional patch for xwayland-satellite in niri's case.
https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/180

---

#### Wlroots/sway fix:
It seems that the wlroots/sway team gave up on the actual upstream fix and have taken a pragmatic if unofficial approach to implementing a fix. Say what you will but **that's the reason why they haven't had this issue for over a year**.
https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4606
https://github.com/swaywm/sway/pull/8063

***

Given the amount of participants here, I really think that the upstream fix ought to be pushed along. I personally just don't know who to bother about it.
